export const experiences = [
  {
    title: "Frontend Internship #1",
    location: "Singapore",
    companyName: "AVPN",
    companyWeb: "https://avpn.asia/",
    companyType: "Social Company",
    image: "/frame33.png",
    backgroundColor: "#E41F18",
    textColor: "dark",
    gradient:
      "linear-gradient(to bottom, rgba(24,221,228,0) 0%,rgb(228,31,24,1) 100%)",
    period: "May - Aug 2022",
    periodTime: "4",
    role: "Frontend Engineer Intern",
    jobdesk: [
      "Designed user interface (UI) and user experience (UX) for the website project using Figma design tool.",
      "Created mockup prototypes for the website project using ReactJs, incorporating previously designed UI/UX.",
      "Managed mockup data using the nocode Airtable application to ensure data reliability and consistency throughout the project development",
    ],
  },
  {
    title: "Frontend Internship #2",
    location: "Jakarta Timur",
    companyName: "Sekolah.mu",
    companyWeb: "https://www.sekolah.mu/",
    companyType: "Edu Tech",
    image: "/fra.png",
    backgroundColor: "#fff",
    textColor: "light",
    gradient:
      "linear-gradient(to bottom, rgba(255,255,255,0) 0%,rgba(255,255,255,1) 100%)",
    period: "(Sep - Dec 2022)",
    periodTime: "4",
    role: "Frontend Engineer Intern",
    jobdesk: [
      "Designing 3 website components for design system",
      "Creating unit test for each component",
      "Achieve 95% coverage test on unit test for each component",
      "Participating to improve feature on payment page",
    ],
  },
  {
    title: "Frontend Internship #3",
    location: "Bandung",
    companyName: "Antares.id",
    companyweb: "https://antares.id/",
    companyType: "IOT Service",
    image: "/Antares.png",
    backgroundColor: "#fff",
    textColor: "light",
    gradient:
      "linear-gradient(to bottom, rgba(255,255,255,0) 0%,rgba(255,255,255,1) 100%)",
    period: "(Jan - Jun 2023)",
    periodTime: "6",
    role: "Developer Intern",
    jobdesk: [
      "Develop 5 simple sub menus for application needs such as create the database, create API, and front-end view",
      "Fix and improve more than 10 sub menu",
    ],
  },
];
